### ISSUE TITLE
react-scripts 1.0.8同步更新

### ISSUE THREAD

**Issue by notreami** [qiqiboy/tiger-new#3]
react-scripts 1.0.8出来了，该项目还在继续维护嘛？是否考虑同步更新下？

**Comment by qiqiboy** [comment]
会不定期维护的，但是因为作为工具，不会很频繁，以稳定为主。

**Comment by notreami** [comment]
回复好快啊！能继续维护很棒哈。
react-scripts 确实缺少稳定性，一天连升3个版本了，紧跟是很麻烦的事情。

**Comment by qiqiboy** [comment]
tiger-new更新到v2

* webpack更新到2.x
* 更好的持久化缓存
* 其它webpack相关插件工具的更新
